apiVersion: v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: harshalbadade/multi-server
          ports:
            - containerPort: 5000
          # define set of environment variables for server to have communication with redis and postgres
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
            #value for this environment variable is set from the command line to create secret
            # syntax: kubectl create secret generic <secret_name> --from-literal key=value
            # e.g.    kubectl create secret generic pgpassword --from-literal PGPASSWORD=1234
            # the reference from above secret_name is given here as a password value
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD