apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  templates:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: harshalbadade/multi-worker
          # inorder to have communication between redis pod and multi worker pod
          # we have to define set of environment variables
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'